-- 코드를 입력하세요
SELECT HALF.FLAVOR

FROM FIRST_HALF AS HALF
LEFT JOIN ICECREAM_INFO AS INFO
ON HALF.FLAVOR = INFO.FLAVOR
WHERE INFO.INGREDIENT_TYPE = 'fruit_based' AND HALF.TOTAL_ORDER > 3000
ORDER BY HALF.TOTAL_ORDER DESC