-- 코드를 입력하세요
SELECT T1.ANIMAL_ID, T1.ANIMAL_TYPE, T1.NAME
FROM (SELECT * 
     FROM ANIMAL_INS
     WHERE SEX_UPON_INTAKE LIKE '%Intact%') AS T1
LEFT JOIN ANIMAL_OUTS AS T2
ON T1.ANIMAL_ID = T2.ANIMAL_ID
WHERE SEX_UPON_OUTCOME LIKE '%Spayed%' or 
SEX_UPON_OUTCOME LIKE '%Neutered%'
ORDER BY T1.ANIMAL_ID