-- 코드를 입력하세요
SELECT T1.CATEGORY, SUM(SALES) AS TOTAL_SALES
FROM BOOK AS T1
LEFT JOIN BOOK_SALES AS T2
ON T1.BOOK_ID = T2.BOOK_ID
WHERE DATE_FORMAT(SALES_DATE,  '%Y-%m') = '2022-01'
GROUP BY T1.CATEGORY
ORDER BY T1.CATEGORY ASC