-- 코드를 입력하세요
SELECT T1.PRODUCT_ID, T1.PRODUCT_NAME, SUM(AMOUNT)* PRICE AS TOTAL_PRICE
FROM FOOD_PRODUCT AS T1
LEFT JOIN FOOD_ORDER AS T2
ON T1.PRODUCT_ID = T2.PRODUCT_ID
WHERE DATE_FORMAT(PRODUCE_DATE, '%Y-%m') = '2022-05'
GROUP BY PRODUCT_NAME 
ORDER BY TOTAL_PRICE DESC, PRODUCT_ID ASC