-- 코드를 입력하세요
SELECT EXTRACT(hour from datetime) as HOUR, count(animal_id) as COUNT
FROM ANIMAL_OUTS
WHERE TIME(DATETIME)>='09:00:00' and TIME(DATETIME)<='19:59:59'
GROUP BY HOUR(DATETIME)
ORDER BY HOUR(DATETIME)