-- 코드를 입력하세요
SELECT BOOK_ID,	AUTHOR_NAME, DATE_FORMAT(PUBLISHED_DATE, '%Y-%m-%d') AS PUBLISHED_DATE
FROM BOOK AS T1
LEFT JOIN AUTHOR AS T2
ON T1.AUTHOR_ID = T2.AUTHOR_ID
WHERE T1.CATEGORY = '경제'
ORDER BY PUBLISHED_DATE ASC