# 입양일 보호시작일 보다 빠른 애들 
# 보호시작일 순으로 

SELECT
T1.ANIMAL_ID, T1.NAME
FROM ANIMAL_INS AS T1 
LEFT JOIN ANIMAL_OUTS AS T2 ON T2.ANIMAL_ID = T1.ANIMAL_ID 

WHERE T1.DATETIME > T2.DATETIME
ORDER BY T1.DATETIME